/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'Index.': typeof import('./../../components/core/layouts/zen-user/index..vue')['default']
    LoginLeftView: typeof import('./../../components/core/views/login/LoginLeftView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSubmenu: typeof import('./../../components/core/layouts/zen-sidebar-menu/widget/SidebarSubmenu.vue')['default']
    ZenBackToBefore: typeof import('./../../components/core/base/zen-back-to-before/index.vue')['default']
    ZenBreadcrumb: typeof import('./../../components/core/layouts/zen-breadcrumb/index.vue')['default']
    ZenButtonMore: typeof import('./../../components/core/forms/zen-button-more/index.vue')['default']
    ZenButtonTable: typeof import('./../../components/core/forms/zen-button-table/index.vue')['default']
    ZenChat: typeof import('./../../components/core/layouts/zen-chat/index.vue')['default']
    ZenDragVerify: typeof import('./../../components/core/forms/zen-drag-verify/index.vue')['default']
    ZenFormActions: typeof import('./../../components/core/forms/zen-form-actions/index.vue')['default']
    ZenFormAuth: typeof import('./../../components/core/forms/zen-form-auth/index.vue')['default']
    ZenGlobalSearch: typeof import('./../../components/core/layouts/zen-global-search/index.vue')['default']
    ZenHeaderBar: typeof import('./../../components/core/layouts/zen-header-bar/index.vue')['default']
    ZenIconButton: typeof import('./../../components/core/widget/zen-icon-button/index.vue')['default']
    ZenLanguage: typeof import('./../../components/core/layouts/zen-language/index.vue')['default']
    ZenLogo: typeof import('./../../components/core/base/zen-logo/index.vue')['default']
    ZenNotification: typeof import('./../../components/core/layouts/zen-notification/index.vue')['default']
    ZenPageContent: typeof import('./../../components/core/layouts/zen-page-content/index.vue')['default']
    ZenSearchBar: typeof import('./../../components/core/forms/zen-search-bar/index.vue')['default']
    ZenSetting: typeof import('./../../components/core/layouts/zen-setting/index.vue')['default']
    ZenSidebarMenu: typeof import('./../../components/core/layouts/zen-sidebar-menu/index.vue')['default']
    ZenSvgIcon: typeof import('./../../components/core/base/zen-svg-icon/index.vue')['default']
    ZenTable: typeof import('./../../components/core/tables/zen-table/index.vue')['default']
    ZenTableHeader: typeof import('./../../components/core/tables/zen-table-header/index.vue')['default']
    ZenUserMenu: typeof import('./../../components/core/layouts/zen-header-bar/widget/ZenUserMenu.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
