/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LoginLeftView: typeof import('./../../components/core/views/login/LoginLeftView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSubmenu: typeof import('./../../components/core/layouts/Wn-sidebar-menu/widget/SidebarSubmenu.vue')['default']
    WnBackToBefore: typeof import('./../../components/core/layouts/Wn-back-to-before/index.vue')['default']
    WnBreadcrumb: typeof import('./../../components/core/layouts/Wn-breadcrumb/index.vue')['default']
    WnButton: typeof import('./../../components/core/base/Wn-button/index.vue')['default']
    WnButtonMore: typeof import('./../../components/core/forms/Wn-button-more/index.vue')['default']
    WnButtonTable: typeof import('./../../components/core/forms/Wn-button-table/index.vue')['default']
    WnDatePicker: typeof import('./../../components/core/forms/Wn-date-picker/index.vue')['default']
    WnDateRangePicker: typeof import('./../../components/core/forms/Wn-date-range-picker/index.vue')['default']
    WnDragVerify: typeof import('./../../components/core/forms/Wn-drag-verify/index.vue')['default']
    WnExcelExport: typeof import('./../../components/core/forms/Wn-excel-export/index.vue')['default']
    WnExcelImport: typeof import('./../../components/core/forms/Wn-excel-import/index.vue')['default']
    WnFooter: typeof import('./../../components/core/layouts/Wn-footer/index.vue')['default']
    WnForm: typeof import('./../../components/core/forms/Wn-form/index.vue')['default']
    WnGlobalSearch: typeof import('./../../components/core/layouts/Wn-global-search/index.vue')['default']
    WnHeaderBar: typeof import('./../../components/core/layouts/Wn-header-bar/index.vue')['default']
    WnIconButton: typeof import('./../../components/core/widget/Wn-icon-button/index.vue')['default']
    WnLanguage: typeof import('./../../components/core/layouts/Wn-header-bar/widget/WnLanguage.vue')['default']
    WnLogo: typeof import('./../../components/core/base/Wn-logo/index.vue')['default']
    WnNotification: typeof import('./../../components/core/layouts/Wn-header-bar/widget/WnNotification.vue')['default']
    WnPageContent: typeof import('./../../components/core/layouts/Wn-page-content/index.vue')['default']
    WnSearchBar: typeof import('./../../components/core/forms/Wn-search-bar/index.vue')['default']
    WnSetting: typeof import('./../../components/core/layouts/Wn-header-bar/widget/WnSetting.vue')['default']
    WnSidebarMenu: typeof import('./../../components/core/layouts/Wn-sidebar-menu/index.vue')['default']
    WnSvgIcon: typeof import('./../../components/core/base/Wn-svg-icon/index.vue')['default']
    WnTable: typeof import('./../../components/core/tables/Wn-table/index.vue')['default']
    WnTableHeader: typeof import('./../../components/core/tables/Wn-table-header/index.vue')['default']
    WnThemeToggle: typeof import('./../../components/core/layouts/Wn-header-bar/widget/WnThemeToggle.vue')['default']
    WnUserMenu: typeof import('./../../components/core/layouts/Wn-header-bar/widget/WnUserMenu.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
